name: Lavarun
version: '${project.version}'
main: me.lished.lavarun.Lavarun
api-version: '1.20'
libraries:
  - org.jetbrains.kotlin:kotlin-maven-plugin:1.9.22
author: Lished
depend:
  - Multiverse-Core
  - HolographicDisplays
  - FastAsyncWorldEdit
  - WorldEdit
softdepend:
  - ProtocolSupport
commands:
  join:
    description: Join
  leave:
    description: Leave
  start:
    description: Start
permissions: {}